version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - mysql
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: laravel_composer
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    entrypoint: ["composer"]
    networks:
      - laravel

  artisan:
    image: laravelsail/php82-composer
    container_name: laravel_artisan
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    entrypoint: ["php", "/var/www/artisan"]
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
